
package GUI;

import civitas.CasillaCalle;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class CasillaActualCallePanel extends javax.swing.JPanel {
    private CasillaCalle calle;
    
    public void setCalle (CasillaCalle calle){
        this.calle = calle;
        
        String propietario;
        if (calle.tienePropietario())
            propietario = calle.getPropietario().getNombre();
        else
            propietario = "no tiene";
        
        textFieldPropietario.setText(propietario);
        textFieldCompra.setText(Float.toString(calle.getPrecioCompra()));
        textFieldEdificar.setText(Float.toString(calle.getPrecioEdificar()));
        //
        textFieldAlquiler.setText(Float.toString(calle.getPrecioAlquilerCompleto()));
        
        repaint();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ///////////////////////////////////////////////////////////////////////
    // Código automatico:
    
    /**
     * Creates new form CasillaCallePanel
     */
    public CasillaActualCallePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldPropietario = new javax.swing.JTextField();
        labelCompra = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelEdificar = new javax.swing.JLabel();
        labelAlquiler = new javax.swing.JLabel();
        textFieldCompra = new javax.swing.JTextField();
        textFieldEdificar = new javax.swing.JTextField();
        labelPropietario = new javax.swing.JLabel();
        textFieldAlquiler = new javax.swing.JTextField();

        textFieldPropietario.setEditable(false);
        textFieldPropietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldPropietario.setText("jTextField2");
        textFieldPropietario.setBorder(null);

        labelCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCompra.setText("Compra:");

        labelPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPrecio.setText("PRECIOS");

        labelEdificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEdificar.setText("Edificar:");

        labelAlquiler.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAlquiler.setText("Alquiler");

        textFieldCompra.setEditable(false);
        textFieldCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldCompra.setText("jTextField2");
        textFieldCompra.setBorder(null);

        textFieldEdificar.setEditable(false);
        textFieldEdificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldEdificar.setText("jTextField2");
        textFieldEdificar.setBorder(null);

        labelPropietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPropietario.setText("Propietario:");

        textFieldAlquiler.setEditable(false);
        textFieldAlquiler.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldAlquiler.setText("jTextField2");
        textFieldAlquiler.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAlquiler)
                            .addComponent(labelEdificar)
                            .addComponent(labelCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelPrecio)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelPropietario)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompra)
                    .addComponent(textFieldCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEdificar)
                    .addComponent(textFieldEdificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlquiler)
                    .addComponent(textFieldAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAlquiler;
    private javax.swing.JLabel labelCompra;
    private javax.swing.JLabel labelEdificar;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelPropietario;
    private javax.swing.JTextField textFieldAlquiler;
    private javax.swing.JTextField textFieldCompra;
    private javax.swing.JTextField textFieldEdificar;
    private javax.swing.JTextField textFieldPropietario;
    // End of variables declaration//GEN-END:variables
}
