
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaSorpresa;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class CasillaActualPanel extends javax.swing.JPanel {
    private Casilla casilla;
    
    public void setCasillaActual (Casilla casilla){
        this.casilla = casilla;        
        
        // Imprimimos la información del jugador con los tres campos de texto
        textFieldNombre.setText(this.casilla.getNombre());
        
        String tipo;
        if (casilla instanceof CasillaCalle)
            tipo = "calle";
        else if (casilla instanceof CasillaSorpresa)
            tipo = "sorpresa";
        else
            tipo = "descanso";
        textFieldTipoCasilla.setText(tipo);
        
        
        panelCasillaCalle.removeAll();
        if (casilla instanceof CasillaCalle){   // SOLO si es una casilla del tipo calle imprime los precios, el propietario,...
            
            CasillaActualCallePanel vistaCalle = new CasillaActualCallePanel();
            vistaCalle.setCalle((CasillaCalle) casilla);
            panelCasillaCalle.add(vistaCalle);
            panelCasillaCalle.setVisible(true);
            repaint();
        }
        else
            panelCasillaCalle.setVisible(false);
        
        
        repaint();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    //////////////////////////////////////////////////////////////////////
    // Código automatico:
    
    /**
     * Creates new form CasillaPanel
     */
    public CasillaActualPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTipoCasilla = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTipoCasilla = new javax.swing.JTextField();
        panelCasillaCalle = new javax.swing.JPanel();

        labelTipoCasilla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTipoCasilla.setText("Casilla de tipo:");

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTitulo.setText("CASILLA ACTUAL:");

        textFieldNombre.setEditable(false);
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textFieldNombre.setText("jTextField1");
        textFieldNombre.setBorder(null);

        textFieldTipoCasilla.setEditable(false);
        textFieldTipoCasilla.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldTipoCasilla.setText("jTextField2");
        textFieldTipoCasilla.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCasillaCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTipoCasilla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldTipoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitulo)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoCasilla)
                    .addComponent(textFieldTipoCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCasillaCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTipoCasilla;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCasillaCalle;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTipoCasilla;
    // End of variables declaration//GEN-END:variables
}
