
package GUI;

import civitas.CivitasJuego;
import civitas.Diario;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import javax.swing.JOptionPane;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class CivitasView extends javax.swing.JFrame implements Vista {
    private CivitasJuego juego;
    
    public void setCivitasJuego (CivitasJuego juego){
        this.juego = juego;
        this.setVisible(true);
    }
    
    @Override
    public void actualiza(){
        panelJugador.setJugador(juego.getJugadorActual());
        panelCasilla.setCasillaActual(juego.getTablero().getCasilla(juego.getJugadorActual().getCasillaActual()));
        panelTablero.setTablero(juego.getTablero(),juego.getJugadores());
        
        // Ocultamos la informacion del ranking
        labelRanking.setVisible(false);
        textAreaRanking.setVisible(false);
        
        // Si estamos en el final del juego, mostramos el ranking:
        if (this.juego.finalDelJuego())
            this.mostrarRanking();
        
        repaint();
        revalidate();
    }
    
    @Override
    public void pausa(){
    int val= JOptionPane.showConfirmDialog(null, "¿Continuar?",
            "Siguiente paso", JOptionPane.YES_NO_OPTION);
    
    if (val==1) System.exit(0);
    }
    
    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operacion){
        textFieldOperacion.setText(operacion.toString());
        repaint();
    }
    
    // Metodo añadido por mi para hacer más clara la lectura del metodo actualiza() de esta misma clase
    private void mostrarRanking(){
        // En este metodo NO aplicamos el metodo ranking(), de eso se encarga el controlador
        textAreaRanking.setText("¡El ganador es el jugador " +juego.getJugadores().get(0).getNombre() +"!\n¡Felicidades!\n\nEl ranking final es:");
        for (int i = 0; i < juego.getJugadores().size(); i++){
            int numClasificado = i + 1;
            textAreaRanking.append("\n" +numClasificado + "o --> " +juego.getJugadores().get(i).getNombre());
        }
        
        labelRanking.setVisible(true);
        textAreaRanking.setVisible(true);
    }
    
    @Override
    public void mostrarEventos(){
        if (Diario.getInstance().eventosPendientes()){
            DiarioDialog diarioD = new DiarioDialog(this);
        }
    }
    
    @Override
    public Respuesta comprar(){
        int opcion= 1-JOptionPane.showConfirmDialog(null, "¿Quieres comprar la calle actual?", 
                "Compra", JOptionPane.YES_NO_OPTION);
        // Si el usuario elige "NO", el indice será 0. Si elige "SÍ", será 1.
        return Respuesta.values()[opcion];
    }
    
    @Override
    public OperacionInmobiliaria elegirOperacion(){
        GestionarDialog gestionD = new GestionarDialog(this);
        int indiceGestion = gestionD.getGestion();
        
        return OperacionInmobiliaria.values()[indiceGestion];
    }

    @Override
    public int elegirPropiedad(){
        PropiedadDialog propiedadD = new PropiedadDialog(this,juego.getJugadorActual());
        int indicePropiedad = propiedadD.getPropiedad();
        
        return indicePropiedad;
    }

    

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ///////////////////////////////////////////////////////////////////////
    // Código creado automaticamente:    
    
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
        labelRanking.setVisible(false);
        textAreaRanking.setVisible(false);
        setLocationRelativeTo(null);
        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableroPanel1 = new GUI.TableroPanel();
        TituloCivitas = new javax.swing.JLabel();
        panelJugador = new GUI.JugadorPanel();
        panelCasilla = new GUI.CasillaActualPanel();
        panelTablero = new GUI.TableroPanel();
        labelOperacion = new javax.swing.JLabel();
        textFieldOperacion = new javax.swing.JTextField();
        labelRanking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaRanking = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloCivitas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloCivitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloCivitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoCivitas.png"))); // NOI18N

        labelOperacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelOperacion.setText("SIGUIENTE OPERACION:");

        textFieldOperacion.setEditable(false);
        textFieldOperacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldOperacion.setText("AVANZAR");
        textFieldOperacion.setBorder(null);

        labelRanking.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelRanking.setText("RANKING:");

        textAreaRanking.setEditable(false);
        textAreaRanking.setColumns(20);
        textAreaRanking.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textAreaRanking.setRows(5);
        textAreaRanking.setAutoscrolls(false);
        textAreaRanking.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setViewportView(textAreaRanking);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(255, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldOperacion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addComponent(panelJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTablero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRanking))
                        .addGap(44, 44, 44)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1034, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(TituloCivitas, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(TituloCivitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(panelCasilla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(labelRanking)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)))
                                .addGap(431, 431, 431))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(panelJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelOperacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textFieldOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloCivitas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelOperacion;
    private javax.swing.JLabel labelRanking;
    private GUI.CasillaActualPanel panelCasilla;
    private GUI.JugadorPanel panelJugador;
    private GUI.TableroPanel panelTablero;
    private GUI.TableroPanel tableroPanel1;
    private javax.swing.JTextArea textAreaRanking;
    private javax.swing.JTextField textFieldOperacion;
    // End of variables declaration//GEN-END:variables
}
