
package GUI;

import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class JugadorPanel extends javax.swing.JPanel {
    private Jugador jugador;
    
    public void setJugador (Jugador jugador){
        this.jugador = jugador;        
        
        // Imprimimos la información del jugador con los tres campos de texto
        textFieldNombre.setText(this.jugador.getNombre());
        textFieldSaldo.setText(Float.toString(this.jugador.getSaldo()));
        textFieldEspeculador.setText(Boolean.toString(this.jugador.getEsJugadorEspeculador()));
        
        // Imprimimos sus propiedades
        this.rellenaPropiedades(this.jugador.getPropiedades());
        
        repaint();
        revalidate();
    }
    
    public void rellenaPropiedades(ArrayList<CasillaCalle> lista){
        // Se elimina la información antigua
        propiedadesPanel.removeAll();
        
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);

            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /////////////////////////////////////////////////////////
    // Codigo automatico:
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
        propiedadesPanel.setLayout(new javax.swing.BoxLayout(propiedadesPanel, javax.swing.BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelSaldo = new javax.swing.JLabel();
        labelJugador = new javax.swing.JLabel();
        labelEspeculador = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldSaldo = new javax.swing.JTextField();
        textFieldEspeculador = new javax.swing.JTextField();
        labelPropiedades = new javax.swing.JLabel();
        propiedadesPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(291, 322));
        setMinimumSize(new java.awt.Dimension(291, 322));

        labelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelSaldo.setText("Saldo:");

        labelJugador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelJugador.setText("JUGADOR");

        labelEspeculador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEspeculador.setText("Especulador:");

        textFieldNombre.setEditable(false);
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textFieldNombre.setText("jTextField1");
        textFieldNombre.setBorder(null);

        textFieldSaldo.setEditable(false);
        textFieldSaldo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldSaldo.setText("jTextField2");
        textFieldSaldo.setBorder(null);

        textFieldEspeculador.setEditable(false);
        textFieldEspeculador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldEspeculador.setText("jTextField2");
        textFieldEspeculador.setBorder(null);

        labelPropiedades.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPropiedades.setText("Propiedades:");

        propiedadesPanel.setLayout(new javax.swing.BoxLayout(propiedadesPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelSaldo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelJugador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelEspeculador)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelPropiedades))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJugador)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSaldo)
                    .addComponent(textFieldSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEspeculador)
                    .addComponent(textFieldEspeculador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPropiedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propiedadesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEspeculador;
    private javax.swing.JLabel labelJugador;
    private javax.swing.JLabel labelPropiedades;
    private javax.swing.JLabel labelSaldo;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JTextField textFieldEspeculador;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldSaldo;
    // End of variables declaration//GEN-END:variables
}
