
package GUI;

import civitas.CasillaCalle;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class PropiedadPanel extends javax.swing.JPanel {
    private CasillaCalle propiedad;
    
    public void setPropiedad (CasillaCalle propiedad){
        this.propiedad = propiedad;
        
        // Imprimimos la información del la casilla del jugador en estos tres campos de texto
        textFieldNombre.setText(this.propiedad.getNombre());
        textFieldCasas.setText(Integer.toString(this.propiedad.getNumCasas()));
        textFieldHoteles.setText(Integer.toString(this.propiedad.getNumHoteles()));
        repaint();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ////////////////////////////////////////////////////////////7
    // Código automatico:
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldNombre = new javax.swing.JTextField();
        LabelCasas = new javax.swing.JLabel();
        LabelHoteles = new javax.swing.JLabel();
        textFieldCasas = new javax.swing.JTextField();
        textFieldHoteles = new javax.swing.JTextField();

        textFieldNombre.setEditable(false);
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textFieldNombre.setText("jTextField1");
        textFieldNombre.setBorder(null);

        LabelCasas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelCasas.setText("Casas:");

        LabelHoteles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LabelHoteles.setText("Hoteles:");

        textFieldCasas.setEditable(false);
        textFieldCasas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldCasas.setText("jTextField2");
        textFieldCasas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textFieldHoteles.setEditable(false);
        textFieldHoteles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textFieldHoteles.setText("jTextField3");
        textFieldHoteles.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelCasas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelHoteles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCasas)
                    .addComponent(textFieldCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelHoteles)
                    .addComponent(textFieldHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCasas;
    private javax.swing.JLabel LabelHoteles;
    private javax.swing.JTextField textFieldCasas;
    private javax.swing.JTextField textFieldHoteles;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
