
package GUI;

import civitas.Jugador;
import civitas.Tablero;
import java.util.ArrayList;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class TableroPanel extends javax.swing.JPanel {
    private Tablero tablero;
    
    
    public void setTablero (Tablero tablero, ArrayList<Jugador> jugadores){
        this.tablero = tablero;
        
        // Asignamos a cada casilla su informacion. Esto actualizará tanto el nombre de la casilla como las fichas de jugador
        casilla1.setCasillaTablero(tablero.getCasillas().get(0), jugadores, tablero.getCasillas());
        casilla2.setCasillaTablero(tablero.getCasillas().get(1), jugadores, tablero.getCasillas());
        casilla3.setCasillaTablero(tablero.getCasillas().get(2), jugadores, tablero.getCasillas());
        casilla4.setCasillaTablero(tablero.getCasillas().get(3), jugadores, tablero.getCasillas());
        casilla5.setCasillaTablero(tablero.getCasillas().get(4), jugadores, tablero.getCasillas());
        casilla6.setCasillaTablero(tablero.getCasillas().get(5), jugadores, tablero.getCasillas());
        casilla7.setCasillaTablero(tablero.getCasillas().get(6), jugadores, tablero.getCasillas());
        casilla8.setCasillaTablero(tablero.getCasillas().get(7), jugadores, tablero.getCasillas());
        casilla9.setCasillaTablero(tablero.getCasillas().get(8), jugadores, tablero.getCasillas());
        casilla10.setCasillaTablero(tablero.getCasillas().get(9), jugadores, tablero.getCasillas());
        casilla11.setCasillaTablero(tablero.getCasillas().get(10), jugadores, tablero.getCasillas());
        casilla12.setCasillaTablero(tablero.getCasillas().get(11), jugadores, tablero.getCasillas());
        casilla13.setCasillaTablero(tablero.getCasillas().get(12), jugadores, tablero.getCasillas());
        casilla14.setCasillaTablero(tablero.getCasillas().get(13), jugadores, tablero.getCasillas());
        casilla15.setCasillaTablero(tablero.getCasillas().get(14), jugadores, tablero.getCasillas());
        casilla16.setCasillaTablero(tablero.getCasillas().get(15), jugadores, tablero.getCasillas());
        casilla17.setCasillaTablero(tablero.getCasillas().get(16), jugadores, tablero.getCasillas());
        casilla18.setCasillaTablero(tablero.getCasillas().get(17), jugadores, tablero.getCasillas());
        casilla19.setCasillaTablero(tablero.getCasillas().get(18), jugadores, tablero.getCasillas());
        casilla20.setCasillaTablero(tablero.getCasillas().get(19), jugadores, tablero.getCasillas());
        
        // Añadimos los nombres de los jugadores a la explicación que se encuentra en el centro del tablero,
        // para poder saber en cualquier momento qué color representa a cada uno
        // El jugador 1 siempre será el de color rojo, el segundo el azul, el tercero el verde y el cuarto el amarillo :)
        textFieldRojo.setText(jugadores.get(0).getNombre());
        textFieldAzul.setText(jugadores.get(1).getNombre());
        textFieldVerde.setText(jugadores.get(2).getNombre());
        textFieldAmarillo.setText(jugadores.get(3).getNombre());
        
        repaint();
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    //////////////////////////////////////////////////////////////////////
    // Codigo generado automaticamente:
    
    /**
     * Creates new form TableroPanel
     */
    public TableroPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casilla1 = new GUI.TableroCasillasPanel();
        casilla2 = new GUI.TableroCasillasPanel();
        casilla3 = new GUI.TableroCasillasPanel();
        casilla4 = new GUI.TableroCasillasPanel();
        casilla5 = new GUI.TableroCasillasPanel();
        casilla6 = new GUI.TableroCasillasPanel();
        casilla7 = new GUI.TableroCasillasPanel();
        casilla20 = new GUI.TableroCasillasPanel();
        casilla19 = new GUI.TableroCasillasPanel();
        casilla18 = new GUI.TableroCasillasPanel();
        casilla17 = new GUI.TableroCasillasPanel();
        casilla16 = new GUI.TableroCasillasPanel();
        casilla15 = new GUI.TableroCasillasPanel();
        casilla14 = new GUI.TableroCasillasPanel();
        casilla13 = new GUI.TableroCasillasPanel();
        casilla12 = new GUI.TableroCasillasPanel();
        casilla11 = new GUI.TableroCasillasPanel();
        casilla10 = new GUI.TableroCasillasPanel();
        casilla9 = new GUI.TableroCasillasPanel();
        casilla8 = new GUI.TableroCasillasPanel();
        labelFlecha = new javax.swing.JLabel();
        panelExplicacion = new javax.swing.JPanel();
        labelRojo = new javax.swing.JLabel();
        labelTituloExplicacion = new javax.swing.JLabel();
        labelAzul = new javax.swing.JLabel();
        labelVerde = new javax.swing.JLabel();
        labelAmarillo = new javax.swing.JLabel();
        textFieldRojo = new javax.swing.JTextField();
        textFieldAzul = new javax.swing.JTextField();
        textFieldVerde = new javax.swing.JTextField();
        textFieldAmarillo = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        casilla1.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla1.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla1.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla2.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla2.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla2.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla3.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla3.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla3.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla4.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla4.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla4.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla5.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla5.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla5.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla6.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla6.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla6.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla7.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla7.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla7.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla20.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla20.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla20.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla19.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla19.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla19.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla18.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla18.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla18.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla17.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla17.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla17.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla16.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla16.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla16.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla15.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla15.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla15.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla14.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla14.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla14.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla13.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla13.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla13.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla12.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla12.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla12.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla11.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla11.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla11.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla10.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla10.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla10.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla9.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla9.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla9.setPreferredSize(new java.awt.Dimension(102, 79));

        casilla8.setMaximumSize(new java.awt.Dimension(102, 79));
        casilla8.setMinimumSize(new java.awt.Dimension(102, 79));
        casilla8.setPreferredSize(new java.awt.Dimension(102, 79));

        labelFlecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FlechaOrden.png"))); // NOI18N

        labelRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleRed.png"))); // NOI18N
        labelRojo.setText("--->");

        labelTituloExplicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelTituloExplicacion.setText("Qué ficha representa a cada jugador:");

        labelAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleBlue.png"))); // NOI18N
        labelAzul.setText("--->");

        labelVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleGreen.png"))); // NOI18N
        labelVerde.setText("--->");

        labelAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleYellow.png"))); // NOI18N
        labelAmarillo.setText("--->");

        textFieldRojo.setEditable(false);
        textFieldRojo.setText("jTextField1");

        textFieldAzul.setEditable(false);
        textFieldAzul.setText("jTextField2");

        textFieldVerde.setEditable(false);
        textFieldVerde.setText("jTextField3");

        textFieldAmarillo.setEditable(false);
        textFieldAmarillo.setText("jTextField4");

        javax.swing.GroupLayout panelExplicacionLayout = new javax.swing.GroupLayout(panelExplicacion);
        panelExplicacion.setLayout(panelExplicacionLayout);
        panelExplicacionLayout.setHorizontalGroup(
            panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExplicacionLayout.createSequentialGroup()
                .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelExplicacionLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelExplicacionLayout.createSequentialGroup()
                                .addComponent(labelAmarillo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelExplicacionLayout.createSequentialGroup()
                                .addComponent(labelVerde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelExplicacionLayout.createSequentialGroup()
                                .addComponent(labelAzul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelExplicacionLayout.createSequentialGroup()
                                .addComponent(labelRojo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelExplicacionLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelTituloExplicacion)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelExplicacionLayout.setVerticalGroup(
            panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExplicacionLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labelTituloExplicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRojo)
                    .addComponent(textFieldRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAzul)
                    .addComponent(textFieldAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVerde)
                    .addComponent(textFieldVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelExplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAmarillo)
                    .addComponent(textFieldAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(labelFlecha)
                        .addGap(54, 54, 54)
                        .addComponent(panelExplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelFlecha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(casilla20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(casilla19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casilla18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casilla8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casilla9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(casilla10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(panelExplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casilla16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casilla11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.TableroCasillasPanel casilla1;
    private GUI.TableroCasillasPanel casilla10;
    private GUI.TableroCasillasPanel casilla11;
    private GUI.TableroCasillasPanel casilla12;
    private GUI.TableroCasillasPanel casilla13;
    private GUI.TableroCasillasPanel casilla14;
    private GUI.TableroCasillasPanel casilla15;
    private GUI.TableroCasillasPanel casilla16;
    private GUI.TableroCasillasPanel casilla17;
    private GUI.TableroCasillasPanel casilla18;
    private GUI.TableroCasillasPanel casilla19;
    private GUI.TableroCasillasPanel casilla2;
    private GUI.TableroCasillasPanel casilla20;
    private GUI.TableroCasillasPanel casilla3;
    private GUI.TableroCasillasPanel casilla4;
    private GUI.TableroCasillasPanel casilla5;
    private GUI.TableroCasillasPanel casilla6;
    private GUI.TableroCasillasPanel casilla7;
    private GUI.TableroCasillasPanel casilla8;
    private GUI.TableroCasillasPanel casilla9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAmarillo;
    private javax.swing.JLabel labelAzul;
    private javax.swing.JLabel labelFlecha;
    private javax.swing.JLabel labelRojo;
    private javax.swing.JLabel labelTituloExplicacion;
    private javax.swing.JLabel labelVerde;
    private javax.swing.JPanel panelExplicacion;
    private javax.swing.JTextField textFieldAmarillo;
    private javax.swing.JTextField textFieldAzul;
    private javax.swing.JTextField textFieldRojo;
    private javax.swing.JTextField textFieldVerde;
    // End of variables declaration//GEN-END:variables
}
