
package GUI;

import civitas.Casilla;
import civitas.Jugador;
import java.util.ArrayList;

/** autora: @Zoroark828
 * 
 * 
 * 
 */

public class TableroCasillasPanel extends javax.swing.JPanel {
    private Casilla casilla;
    
    public void setCasillaTablero (Casilla casilla, ArrayList<Jugador> jugadores, ArrayList<Casilla> tablero){
        this.casilla = casilla;
        
        // Nombre de la casilla:
        textFieldNombre.setText(this.casilla.getNombre());
        
        /////////
        // Para pintar las "fichas" del tablero para cada jugador, hacemos lo siguiente:
        
        labelRed.setVisible(false); // De primeras hacemos que ninguna ficha sea visible
        labelBlue.setVisible(false);
        labelYellow.setVisible(false);
        labelGreen.setVisible(false);
        
        // Con este bucle for comprobamos si algun jugador esta en la casilla actual y actualizamos conforme a ello
        for (Jugador jug:jugadores){
            int casillaJug = jug.getCasillaActual(); // La casilla en la que se encuentra jug
            int indiceCasilla = tablero.indexOf(casilla); // El indice en el tablero de la casilla que ocupa este panel
            
            // Si la casilla en la que está el jugador es igual a la actual...
            if (casillaJug == indiceCasilla){
                int indiceJug = jugadores.indexOf(jug); // Indice del jugador en el array
                
                switch (indiceJug){
                    case 0:
                        labelRed.setVisible(true);  // Si es el jugador 1, se muestra el punto rojo
                        break;
                    case 1:
                        labelBlue.setVisible(true);    // Si es el jugador 2, se muestra el azul
                        break;
                    case 2:
                        labelGreen.setVisible(true);   // ...
                        break;
                    case 3:
                        labelYellow.setVisible(true);  // ...
                        break;
                }
            }
            repaint();
            revalidate();
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ///////////////////////////////////////////////////////////////
    // Codigo generado automaticamente:
    /**
     * Creates new form TableroCasillasPanel
     */
    public TableroCasillasPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        labelRed = new javax.swing.JLabel();
        labelBlue = new javax.swing.JLabel();
        labelGreen = new javax.swing.JLabel();
        labelYellow = new javax.swing.JLabel();

        jLabel2.setText("jLabel1");

        jLabel5.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textFieldNombre.setEditable(false);
        textFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textFieldNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNombre.setText("jTextField1");
        textFieldNombre.setBorder(null);
        textFieldNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleRed.png"))); // NOI18N

        labelBlue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleBlue.png"))); // NOI18N

        labelGreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleGreen.png"))); // NOI18N

        labelYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CircleYellow.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGreen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelYellow)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(textFieldNombre)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBlue)
                    .addComponent(labelGreen)
                    .addComponent(labelYellow)
                    .addComponent(labelRed))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelBlue;
    private javax.swing.JLabel labelGreen;
    private javax.swing.JLabel labelRed;
    private javax.swing.JLabel labelYellow;
    private javax.swing.JTextField textFieldNombre;
    // End of variables declaration//GEN-END:variables
}
